---
# Publish Docker Image to Docker Hub
name: Docker Hub Deployment
on:
  push:
    branches:
      - main

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Display repo branch name related to pull request
        if: ${{ github.ref }}
        run: echo ${{ github.ref }}

      - name: Build and push PROD Docker image
        if: ${{ github.ref == 'refs/heads/main' }}
        id: docker_prod_build
        uses: docker/build-push-action@v2.1.0
        with:
          push: true
          tags: wwt01/devasc-data-formats:latest

      - name: Display PROD image digest
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo Image digest - ${{ steps.docker_prod_build.outputs.digest }}
